### ISSUE TITLE
Support for JSON PATCH on update

### ISSUE THREAD

**Issue by dpjanes** [sparkfun/phant-manager-http#10]
Issue:
Updating the metadata with JSON POST is (1) really not RESTy (2) blanks out data not in the post. It would be nice to be able to update only certain named fields.

Background:
HTTP 'PATCH' is similar to PUT except that only fields sent should be updated. 
http://tools.ietf.org/html/rfc5789

Solution:
routes.update should detect PATCH and default data as needed.

(I am willing to code this)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
