### ISSUE TITLE
Error: EMFILE

### ISSUE THREAD

**Issue by camilorojasg** [sparkfun/phant-manager-http#12]
Hi.

It looks like a lammer is downloading a .csv file too many times of a stream in my server.
This generates this error when I try to access any page:

> Error: EMFILE: too many open files, scandir '/usr/local/lib/node_modules/phant/node_modules/phant-manager-http/views/partials'
>    at Error (native)

Is there a way to limit the time between downloads? At the moment I'll increase my **ulimit -n** 

Best regards.

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
