### ISSUE TITLE
What is the most effective way to add 3rd party libraries

### ISSUE THREAD

**Issue by schreiaj** [sparkfun/phant-manager-http#2]
In my attempt to add plotting to let folks see the data over time better I was trying to add in D3.js and Rickshaw.js (and it's supporting css) I noticed that all of the css and javascript in this project is concatenated into one file. Makes sense during production but it makes adding in new libraries and maintaining the ones in it a complete pain. 

What would you suggest the most effective/maintainable method to bring them in is?

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
