### ISSUE TITLE
Stream Description File

### ISSUE THREAD

**Issue by dpjanes** [sparkfun/phant-manager-http#5]
**Background**:

When a new stream is created, you are brought to you a page that describes the public key, the private key and so forth. There's also an option to email this to yourself.

**Issue**:

To use this data, typically one will copy each field somewhere else using cut and paste. This is rather tedious.

**Proposed solution**:

A new URL be made available

```
https://data.sparkfun.com/streams/<public>/keys/<private>
```

This will return a JSON record that looks like this (possibly with some other fields)

```
{
    "public_url": "https://data.sparkfun.com/output/<public>",
    "public_key": "###",    
    "private_key": "###",   
    "delete_key": "###"
}
```

The following HTTP headers will be returned

```
Content-Type: application/json
Content-Disposition: attachment; filename="<public_key>.json"
```

(Note: I'm willing to help out coding)

**Comment by bboyho** [comment]
### Phant is No Longer in Operation

Unfortunately Phant, our data-streaming service, is no longer in service and will be discontinued. The system has reached capacity and, like a less-adventurous Cassini, has plunged conclusively into a fiery and permanent retirement. There are several other maker-friendly, data-streaming services and/or IoT platforms available as alternatives. The three we recommend are Blynk, ThingSpeak, and Cayenne. You can read our blog post [ [https://www.sparkfun.com/news/2413](https://www.sparkfun.com/news/2413) ] on the topic for an overview and helpful links for each platform.
